In [1]:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [5]:
import numpy as np

In [13]:
array1d = np.arange(10,100)

print(array1d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [33]:
#array1d = np.random.randint(10,100)
array1d = np.random.randint(10,100, size=50)

In [34]:
array1d

array([98, 51, 23, 29, 71, 15, 76, 68, 80, 29, 95, 98, 77, 61, 81, 23, 19,
       48, 87, 38, 36, 13, 15, 73, 77, 39, 57, 65, 20, 19, 73, 72, 62, 24,
       16, 55, 76, 60, 28, 81, 47, 63, 10, 10, 70, 74, 83, 33, 67, 62])

In [2]:
#Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [36]:
array1d2 = np.random.randint(1,20, size=30)

In [37]:
array1d2

array([14,  7, 16,  8,  2,  5, 16, 15, 18, 11,  3, 16,  6, 13, 11, 13, 11,
        3,  5,  7, 16,  1,  9,  8, 19, 15,  8, 19, 11,  2])

In [39]:
array1d2[0::2]

array([14, 16,  2, 16, 18,  3,  6, 11, 11,  5, 16,  9, 19,  8, 11])

In [ ]:
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [ ]:
array2d = np.random.uniform(-50, 50, (4, 6))

In [50]:
array2d = np.round(array2d, 2)

In [51]:
array2d

array([[-29.54, -39.18, -16.78,  36.22,  32.43,  24.13],
       [-34.97, -15.89, -25.07,  47.03, -34.18, -23.79],
       [  7.85,  32.25, -40.8 , -20.91, -44.44, -44.37],
       [  4.73, -40.82,  38.86, -46.01,  16.32,  28.43]])

In [ ]:
#Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [69]:
# no tira - array3d = np.arange((0.0,1.0),(2,3,5))
array3d = np.random.rand(2, 3, 5)
array3d = np.round(array3d, 1)



In [70]:
array3d

array([[[0.5, 0.8, 0.2, 0.1, 0.4],
        [0.2, 0.7, 0.4, 0.1, 0.6],
        [0.9, 0.6, 0.6, 0.7, 0.4]],

       [[0.7, 0.9, 0.2, 0.1, 0.7],
        [0.3, 0.5, 0.8, 0.8, 0.9],
        [0.2, 0.3, 0.9, 0.5, 0.3]]])

Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [71]:
array_vacio_tridimensional =  np.empty((2, 3, 5)) #array vacio

In [72]:
array_vacio_tridimensional

array([[[0.5, 0.8, 0.2, 0.1, 0.4],
        [0.2, 0.7, 0.4, 0.1, 0.6],
        [0.9, 0.6, 0.6, 0.7, 0.4]],

       [[0.7, 0.9, 0.2, 0.1, 0.7],
        [0.3, 0.5, 0.8, 0.8, 0.9],
        [0.2, 0.3, 0.9, 0.5, 0.3]]])

In [ ]:
#Si el valor del array es igual que la media, se reemplaza por "A".

In [76]:
#np.where(array_vacio_tridimensional = np.mean(array_vacio_tridimensional), "A")

media_total = np.mean(array_vacio_tridimensional)

In [77]:
media_total

0.51

In [83]:
media_total=0.5

In [84]:
np.where((array_vacio_tridimensional == media_total), "A", array_vacio_tridimensional)

array([[['A', '0.8', '0.2', '0.1', '0.4'],
        ['0.2', '0.7', '0.4', '0.1', '0.6'],
        ['0.9', '0.6', '0.6', '0.7', '0.4']],

       [['0.7', '0.9', '0.2', '0.1', '0.7'],
        ['0.3', 'A', '0.8', '0.8', '0.9'],
        ['0.2', '0.3', '0.9', 'A', '0.3']]], dtype='<U32')

In [ ]:
#Si el valor del array es mayor que la media, se reemplaza por "B".

In [85]:
np.where((array_vacio_tridimensional > media_total), "B", array_vacio_tridimensional)

array([[['0.5', 'B', '0.2', '0.1', '0.4'],
        ['0.2', 'B', '0.4', '0.1', 'B'],
        ['B', 'B', 'B', 'B', '0.4']],

       [['B', 'B', '0.2', '0.1', 'B'],
        ['0.3', '0.5', 'B', 'B', 'B'],
        ['0.2', '0.3', 'B', '0.5', '0.3']]], dtype='<U32')

In [86]:
#Si el valor del array es menor que la media, se reemplaza por "C".
np.where((array_vacio_tridimensional < media_total), "C", array_vacio_tridimensional)

array([[['0.5', '0.8', 'C', 'C', 'C'],
        ['C', '0.7', 'C', 'C', '0.6'],
        ['0.9', '0.6', '0.6', '0.7', 'C']],

       [['0.7', '0.9', 'C', 'C', '0.7'],
        ['C', '0.5', '0.8', '0.8', '0.9'],
        ['C', 'C', '0.9', '0.5', 'C']]], dtype='<U32')

In [91]:
maximo = np.max(array_vacio_tridimensional)

In [94]:
print(maximo)

0.9


In [93]:
#Si el valor es igual que el máximo, se reemplaza por "D".
np.where((array_vacio_tridimensional == maximo), "D", array_vacio_tridimensional)

array([[['0.5', '0.8', '0.2', '0.1', '0.4'],
        ['0.2', '0.7', '0.4', '0.1', '0.6'],
        ['D', '0.6', '0.6', '0.7', '0.4']],

       [['0.7', 'D', '0.2', '0.1', '0.7'],
        ['0.3', '0.5', '0.8', '0.8', 'D'],
        ['0.2', '0.3', 'D', '0.5', '0.3']]], dtype='<U32')

In [ ]:
#Si el valor es igual que el mínimo, se reemplaza por "E".

In [95]:
minimo = np.min(array_vacio_tridimensional)

In [96]:
print(minimo)

0.1


In [97]:
np.where((array_vacio_tridimensional == minimo), "E", array_vacio_tridimensional)

array([[['0.5', '0.8', '0.2', 'E', '0.4'],
        ['0.2', '0.7', '0.4', 'E', '0.6'],
        ['0.9', '0.6', '0.6', '0.7', '0.4']],

       [['0.7', '0.9', '0.2', 'E', '0.7'],
        ['0.3', '0.5', '0.8', '0.8', '0.9'],
        ['0.2', '0.3', '0.9', '0.5', '0.3']]], dtype='<U32')

In [101]:
np.where((array_vacio_tridimensional == media_total), "A", array_vacio_tridimensional) and
np.where((array_vacio_tridimensional > media_total), "B", array_vacio_tridimensional)

SyntaxError: invalid syntax (566717968.py, line 1)