
¿Qué diferencia hay entre una Serie y un DataFrame?
- Una serie tiene 1 dimensión
- DFes bidimensional y tiene filas y columnas

Es el turno de los DataFrames



In [21]:
import numpy as np
import pandas as pd

In [18]:
#Crea un array de dos dimensiones con 4 filas y 3 columnas.


array_1d = np.random.randint(0, 101, size=(4, 3))


In [19]:
print(array_1d)

[[54 67 99]
 [16 59 85]
 [98 34 86]
 [45 30 86]]


In [22]:
#- Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df = pd.DataFrame(array_1d, columns=["España", "Francia", "Italia"])

In [24]:
df.head()

España  Francia  Italia
0      54       67      99
1      16       59      85
2      98       34      86
3      45       30      86

In [27]:
# Descarga el archivo "medallas" y carga el DataFrame.

df_d2 = pd.read_csv("medallas.csv", index_col=0)


In [29]:
df_d2.head(10)

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [41]:
# - Usando el loc extrae todas las columnas de la fila de Tailandia.

tailandiafila = df_d2.loc[df_d2["País"] == "Tailandia"]

In [42]:
print(tailandiafila)

        País  Oro  Plata  Bronce
7  Tailandia  132    175     278


In [43]:
tailandiafila.head()

País  Oro  Plata  Bronce
7  Tailandia  132    175     278

In [48]:
# - Usando el loc extrae todas las columnas de China e Irán.

pais_china_iran = df_d2.loc[df_d2["País"].isin(["China", "Irán"])]


In [50]:
pais_china_iran.head()

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [49]:
df_china = df_d2.loc[df_d2["País"] == "China"]
df_iran = df_d2.loc[df_d2["País"] == "Irán"]


In [54]:
#- Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

pais_china_iran.loc[::1, "Oro":"Bronce"]

Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

In [61]:
# - Usando el iloc extrae la información de la India. Devolved todas las columnas.

df_india = df_d2.iloc[df_d2[::1, 5,0]]

InvalidIndexError: (slice(None, None, 1), 5, 0)

In [68]:
df_india = df_d2.iloc[5::6]

In [69]:
df_india.head()

País  Oro  Plata  Bronce
6  India  154    202     315

In [71]:
# - Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

impares = df_d2.iloc[1::2]

In [72]:
impares.head()

País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [74]:
# - Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

impares.loc[::1, "Oro":"Bronce"]

Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [76]:
'''-Contesta a las siguientes preguntas:
    - ¿Qué país consiguió más de 200 medallas de oro? 
    - ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
    - ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
    - Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.'''

df_d2.head(10)

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [78]:
medallas_oro= df_d2.loc["Oro" > 200]

TypeError: '>' not supported between instances of 'str' and 'int'